#!/bin/bash

PIDFILE=/run/embci/webui.pid
LOGFILE=/var/log/embci/webui.log
# PORT=8080
PORT=80

mkdir -p $(dirname ${PIDFILE} ${LOGFILE})

nohup python -m embci.webui --port ${PORT} --pid ${PIDFILE} > ${LOGFILE} 2>&1 &
