#!/bin/sh

### BEGIN INIT INFO
# Provides:          EmBCI
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:	 2 3 4 5
# Default-Stop:		 0 1 6
# Short-Description: Embedded BCI service daemon
### END INIT INFO

set -e

python -c 'import embci' || exit 0

case $1 in
	start)
		/etc/init.d/nmbd start
		/etc/init.d/smbd start
		/etc/init.d/samba-ad-dc start
		;;
	stop)
		/etc/init.d/samba-ad-dc stop
		/etc/init.d/smbd stop
		/etc/init.d/nmbd stop
		;;
	reload)
		/etc/init.d/smbd reload
		;;
	restart|force-reload)
		/etc/init.d/nmbd "$1"
		/etc/init.d/smbd "$1"
		/etc/init.d/samba-ad-dc "$1"
		;;
	status)
		status=0
		NMBD_DISABLED=`testparm -s --parameter-name='disable netbios' 2>/dev/null || true`
		SERVER_ROLE=`samba-tool testparm --parameter-name="server role"  2>/dev/null | tail -1 || true`
		if [ "$SERVER_ROLE" != "active directory domain controller" ]; then
			if [ "$NMBD_DISABLED" != "Yes" ]; then
				/etc/init.d/nmbd status || status=$?
			fi
			/etc/init.d/smbd status || status=$?
		else
			/etc/init.d/samba-ad-dc status || status=$?
		fi
		exit $status
		;;
	*)
		echo "Usage: /etc/init.d/samba {start|stop|reload|restart|force-reload|status}"
		exit 1
		;;
esac


PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON_SBIN=/usr/sbin/hostapd
DAEMON_DEFS=/etc/default/hostapd
NAME=hostapd
PIDFILE=/run/hostapd.pid
