#!/usr/bin/env python
# coding=utf-8
'''
File: EmBCI/embci/webui/embci-webui
Author: Hankso
Web: http://github.com/hankso
Time: Mon 26 Nov 2018 17:04:31 CST
'''

import re
import sys

from embci.webui import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
